#cloud-config
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html
package_upgrade: true
packages:
  - curl
  - git

disk_setup:
  /dev/nvme0n1:
    table_type: 'gpt'
    layout: True
    overwrite: True

fs_setup:
  - device: /dev/nvme0n1
    label: None,
    filesystem: ext4
    partition: auto

mounts:
  - [ /dev/nvme0n1p1, /chia/tmp]

write_files:
  - path: /etc/systemd/system/chia-clone.service
    owner: root:root
    content: |
      [Unit]
      Description = Systemd unit for chia clone
      #After = network.target
      Before = chia-plot.service
      [Service]
      Type = oneshot
      RemainAfterExit = true
      User = chechia
      Group = chechia
      WorkingDirectory=/home/chechia
      ExecStart = /usr/bin/git clone https://github.com/Chia-Network/chia-blockchain.git -b latest --recurse-submodules /home/chechia/chia-blockchain
      [Install]
      WantedBy = multi-user.target
  - path: /etc/systemd/system/chia-init.service
    owner: root:root
    content: |
      [Unit]
      Description = Systemd unit for chia check
      [Service]
      Type = oneshot
      RemainAfterExit = true
      User = chechia
      Group = chechia
      WorkingDirectory=/home/chechia/chia-blockchain
      ExecStartPre = /usr/bin/sh install.sh
      ExecStartPre = /home/chechia/chia-blockchain/venv/bin/chia init
      ExecStartPre = /home/chechia/chia-blockchain/venv/bin/chia keys add -f /chia/final/mnemonic
      ExecStart = /home/chechia/chia-blockchain/venv/bin/chia plots add -d /chia/final
      [Install]
      WantedBy = multi-user.target
  - path: /etc/systemd/system/chia-check.service
    owner: root:root
    content: |
      [Unit]
      Description = Systemd unit for chia farm
      After = chia-init.service
      [Service]
      Type = simple
      RemainAfterExit = true
      User = chechia
      Group = chechia
      WorkingDirectory=/home/chechia/chia-blockchain
      ExecStart = /home/chechia/chia-blockchain/venv/bin/chia plots check
      [Install]
      WantedBy = multi-user.target
  - path: /etc/systemd/system/chia-farm.service
    owner: root:root
    content: |
      [Unit]
      Description = Systemd unit for chia farm
      After = chia-init.service
      [Service]
      Type = simple
      RemainAfterExit = true
      User = chechia
      Group = chechia
      WorkingDirectory=/home/chechia/chia-blockchain
      ExecStart = /home/chechia/chia-blockchain/venv/bin/chia start farmer
      [Install]
      WantedBy = multi-user.target
  - path: /home/chechia/fuse_connection.cfg
    owner: chechia:chechia
    content: |
      accountName ${account_name}
      accountKey ${account_key}
      containerName ${container_name}
      #blobEndpoint ${container_fqdn}

runcmd:
  - curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-add-repository https://packages.microsoft.com/ubuntu/20.04/prod
  - sudo apt-get update
  - sudo apt-get install -y blobfuse
  - sudo mkdir -p /chia/final /chia/tmp/blob
  - sudo chown chechia:chechia /home/chechia  /chia/final /chia/tmp/blob
  - sudo chown chechia:chechia /home/chechia/fuse_connection.cfg # !?
  - sudo blobfuse /chia/final --tmp-path=/chia/tmp/blob --config-file=/home/chechia/fuse_connection.cfg -o allow_other -o attr_timeout=240 -o entry_timeout=240 -o negative_timeout=120
  - sudo systemctl start chia-clone
  - sudo systemctl start chia-init
  #- sudo systemctl start chia-check
  - sudo systemctl start chia-farm
