#cloud-config
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html
package_upgrade: true
packages:
  - software-properties-common
  - curl
  - git
  - apache2
  - php8.2
  - php8.2-cli
  - php8.2-common
  - php8.2-curl
  - php8.2-gd
  - php8.2-intl
  - php8.2-mbstring
  - php8.2-mysql
  - php8.2-opcache
  - php8.2-readline
  - php8.2-xml
  - php8.2-xsl
  - php8.2-zip
  - php8.2-bz2
  - libapache2-mod-php8.2
  - mariadb-server
  - mariadb-client

runcmd:
  - sudo apt-get update
