#cloud-config
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html
package_upgrade: true
packages:
  - software-properties-common
  - curl
  - git
  - apache2
  - php8.1
  - php8.1-cli
  - php8.1-common
  - php8.1-curl
  - php8.1-gd
  - php8.1-intl
  - php8.1-mbstring
  - php8.1-mysql
  - php8.1-opcache
  - php8.1-readline
  - php8.1-xml
  - php8.1-xsl
  - php8.1-zip
  - php8.1-bz2
  - libapache2-mod-php8.1
  - mariadb-server
  - mariadb-client

runcmd:
  - sudo apt-get update
